config/routes.rb
require 'sidekiq/web'

Nexttest::Application.routes.draw do

  resources :pages do
    resources :results
  end
  resources :main
  resources :feedbacks

  resources :users
  match '/signup' => 'users#new'

  get    '/login'  => 'sessions#new'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy', :via => :delete

  root :to => 'pages#new'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :user_id, :page_id, :first_answer, :second_answer, :image
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :image, :url

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :username, :email, :password, :password_confirmation, :image

  has_secure_password

  has_many :votes
  has_many :comments
  has_many :pages

  validates :email, :uniqueness => { :case_sensitive => false }, :format => /\w+@\w+\.\w{2,4}/
  validates :username, :uniqueness  => { :case_sensitive => false }, :length => {:minimum => 4}
  validates :password, :length => {:minimum => 6}

  validates_confirmation_of :password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.page_id = params[:page_id]
    @feedback.user_id = current_user.id if current_user
    @feedback.image = generated_filename
    screenshot_selection("#{Rails.root}/public/screenshots/#{Page.find(params[:page_id]).image}", @feedback.image, params[:x_coordinate].to_i, params[:y_coordinate].to_i, params[:width].to_i, params[:height].to_i)
    if @feedback.save
      redirect_to page_results_path(@feedback.page_id)
    else
      render :new
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @page = Page.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html, :js

  def new
    @page = Page.new()
  end

  def create
    @page = Page.new(params[:page])
    @page.image = generated_filename
    @page.user_id = current_user.id if current_user
    ScreenshotsGenerator.perform_async(params[:page][:url], @page.image)

    if @page.save
      respond_with @page, :location => root_path
    else
      render :new
    end
  end


  def show
    @page = Page.find(params[:id])
    @page_url = @page.url.sub(/^https?\:\/\//, '').sub(/^www./,'')
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @feedback_collection = Feedback.find_all_by_page_id(params[:page_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = current_user || User.new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:current_user_id] = user.id
      flash[:success] = "You successfully logged in!"
      redirect_to user
    else
      flash.now[:error] = "Unsuccessful login attempt!"
      render "new"
    end
  end

  def destroy
    session.clear
    flash[:success] = "You successfully logged out!"
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:current_user_id] = @user.id
      flash[:success] = "You have signed up successfully!"
      redirect_to @user
    else
      flash.now[:error] = @user.errors.full_messages.first
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @_current_user ||= session[:current_user_id] &&
                       User.find_by_id(session[:current_user_id])
  end

  def flash_class(level)
    {:notice  => "alert alert-info",
     :success => "alert alert-success",
     :error   => "alert alert-error",
     :alert   => "alert alert-error"}[level]
  end

  def generated_filename
    Array.new(40){[*'0'..'9', *'a'..'z'].sample}.join + '.png'
  end

  def screenshot_selection(current_screenshot, file_name, x_coordinate, y_coordinate, width, height)
    img = Magick::Image.read(current_screenshot)[0]
    chopped = img.crop(x_coordinate, y_coordinate, width, height)
    chopped.write("#{Rails.root}/public/screenshots/crops/#{file_name}")
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper

end

app/helpers/pages_helper.rb
module PagesHelper



end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "jquery.Jcrop" %>

    <%= javascript_include_tag "parsley" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery.Jcrop" %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="user_profile large-12">
        <ul class="nav">
          <%= link_to "Next Test", root_path %>
<!--         <% if current_user %>
          <li><%= link_to "Logout", logout_path, :method => 'delete' %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Signup", signup_path%></li>
        <% end %> -->
        </ul>
<!--         Current Page Image: <%= session[:current_page_image] %>
        Current Page URL: <%= session[:current_page_url] %> -->
      </div>
    </div>
    <%= yield %>


  <script type="text/javascript">
    jQuery(document).foundation('joyride', 'start');
  </script>
  </body>
</html>

app/views/pages/_link.html.erb
<div class="large-4 large-centered columns">
  <span>Copy and share your link:</span>
  <%= text_area_tag :url, "#{request.host_with_port}/pages/#{@page.id}", id: "page-url", class: "text-field" %>
</div>

app/views/pages/create.js.erb
jQuery('.url-form').hide().after("<%= j render partial: 'link', locals: {page: @page} %>")
var url_link = document.getElementById ('page-url');
url_link.focus ();
url_link.select ();

app/views/pages/new.html.erb
<div class="container">
  <div class="row large-6 large-centered columns">
    <h1 class="main-title">Marketers, make your next move.</h1>
    <h2 class="secondary-title">Get actionable A/B tests to run on your landing page.</h2>
  </div>


  <div class="row url-form">
    <div class="large-8 large-centered columns">
      <%= form_for @page, url: pages_path, remote: true, class: "landing-page-form", html: { :"data-validate" => 'parsley', name: "urlInput" } do |f| %>
          <div class="row collapse">
            <div class="large-10 columns">
              <%= f.text_field :url, placeholder: "Type in your landing page link", class: "text-field", type: "text", :"data-type" => "url", :"data-required" => "true", :"data-trigger" => "change", :"data-regexp" => "^https?://", :"data-regexp-message" => "Your link must begin with http:// or https://" %>
            </div>
            <div class="large-2 columns">
              <%= f.submit "Get Screenshot", class: 'button' %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>



<!--
<div>Click and drag to make notes</div>
<div>Add feedback</div>
<div>Share with others</div> -->

app/views/pages/show.html.erb
<% if FileTest.exist?("#{Rails.root}/public/screenshots/#{@page.image}") %>

  <div class="image" id="firstStop">
    <%= image_tag "/screenshots/#{@page.image}", class: "cropbox" %>
  </div>
  <div class="updated_on">Page captured on <%= @page.created_at.strftime("%B %l %Y, %I:%M:%S %p%z")%></div>


  <div class="feedback-bar">
    <div class="row">
      <div class="large-centered" id="secondStop">
        <%= form_for :feedback, url: feedbacks_path do |f| %>
        <%= f.label :first_answer, "What do you like about the Landing Page Optimization on this selection?" %>
        <%= f.text_field :first_answer %>
        <%= f.label :second_answer, "What would you change or test on this selection?" %>
        <%= f.text_field  :second_answer %>
        <%= hidden_field_tag :page_id, "#{@page.id}" %>
        <%= hidden_field_tag :x_coordinate %>
        <%= hidden_field_tag :y_coordinate %>
        <%= hidden_field_tag :width %>
        <%= hidden_field_tag :height %>
        <%= f.submit "Send Feedback", class: 'button', id: "lastStop" %>
        <% end %>
      </div>
    </div>
  </div>

  <% unless cookies[:joyrideEnabled] == "false" %>
  <ol class="joyride-list" data-joyride>
    <li data-text="Sure" data-options="tipAnimation:fade">
      <p>We're struggling with A/B testing <%= @page_url %>. Can you help us?</p>
      <a class="disableTooltips">Stop showing tooltips</a>
    </li>
    <li data-text="Next" data-options="tipAnimation:fade;">
      <p>Here's a screenshot of the landing page. You can select areas of the page and leave annotations.</p>
    </li>
    <li data-text="Let's get started.">
      <p>That's it!</p>
    </li>
  </ol>
  <% end %>

<% else %>

  "Generating screenshot... reload this page in a bit"

<% end %>

app/views/results/index.html.erb
<% @feedback_collection.each do |feedback| %>

<%= image_tag "/screenshots/crops/#{feedback.image}" %>

<p>What do you like about the Landing Page Optimization on this page?</p>
<p><%= feedback.first_answer %></p>
<br>
<p>What would you change or test on this landing page?</p>
<p><%= feedback.second_answer %></p>

<% end %>

app/views/users/_signup_form.html.erb
<div class="form form-stacked">
  <%= form_for @user, url: users_path do |f| %>
    <div class="field">
      <div class="input-prepend">
        <span class="add-on"><i class="icon-user"></i></span>
      <%= f.text_field      :username, placeholder: "Username", autofocus: true%>
      </div><br>
      <div class="input-prepend">
        <span class="add-on"><i class="icon-envelope"></i></span>
        <%= f.email_field     :email,    placeholder: "Email" %>
      </div><br>
      <div class="input-prepend">
        <span class="add-on"><i class="icon-key"></i></span>
        <%= f.password_field  :password, placeholder: "Password" %>
      </div><br>
      <div class="input-prepend">
        <span class="add-on"><i class="icon-key"></i></span>
        <%= f.password_field  :password_confirmation, placeholder: "Confirm password" %>
      </div><br>
      <%= f.file_field      :image %>
    </div>
    <div class="action">
      <%= f.submit "Sign Up", class: "btn btn-success btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/_user_info.html.erb
<div class="user-info">
  <% if user.image.present? %>
    <div class="avatar"><%= link_to user do %>
      <%= image_tag user.image.thumb %>
      <% end %>
    </div>
  <% end %>
    <div class="username"><%= link_to user.username, user %><br></div>
</div>

app/views/users/new.html.erb
<div class="content">
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<%= render "signup_form", :locals => { :user => @user } %>
</div>

app/views/users/show.html.erb
<br><h3 class="user_title"><%= @user.username %></h3><br>